### ISSUE TITLE
SDbot crashes for command "sdbot devices available <device>"

### ISSUE THREAD

**Issue by hansott** [serverdensity/sdbot#4]
Trace:

`2016-03-07T08:34:39.127031+00:00 app[worker.1]: 2016-03-07 08:34:39,126:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.serverdensity.io
2016-03-07T08:34:39.869120+00:00 app[worker.1]: 2016-03-07 08:34:39,868:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.serverdensity.io
2016-03-07T08:34:43.037807+00:00 app[worker.1]: Traceback (most recent call last):
2016-03-07T08:34:43.038155+00:00 app[worker.1]:     opcode, data = self.recv_data()
2016-03-07T08:34:43.038316+00:00 app[worker.1]:     frame = self.recv_frame()
2016-03-07T08:34:43.037839+00:00 app[worker.1]:   File "bin/limbo", line 17, in <module>
2016-03-07T08:34:43.037845+00:00 app[worker.1]:     main(args)
2016-03-07T08:34:43.037918+00:00 app[worker.1]:   File "/app/limbo/limbo.py", line 181, in loop
2016-03-07T08:34:43.037846+00:00 app[worker.1]:   File "/app/limbo/limbo.py", line 285, in main
2016-03-07T08:34:43.037915+00:00 app[worker.1]:     loop(server)
2016-03-07T08:34:43.037970+00:00 app[worker.1]:     events = server.slack.rtm_read()
2016-03-07T08:34:43.037974+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/slackrtm/client.py", line 23, in rtm_read
2016-03-07T08:34:43.038170+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 365, in recv_data
2016-03-07T08:34:43.038405+00:00 app[worker.1]:     return self.frame_buffer.recv_frame()
2016-03-07T08:34:43.038474+00:00 app[worker.1]:     self.recv_header()
2016-03-07T08:34:43.038419+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_abnf.py", line 300, in recv_frame
2016-03-07T08:34:43.038493+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_abnf.py", line 249, in recv_header
2016-03-07T08:34:43.038026+00:00 app[worker.1]:     data = [json.loads(d) for d in self.server.websocket_safe_read()]
2016-03-07T08:34:43.038552+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_abnf.py", line 334, in recv_strict
2016-03-07T08:34:43.038034+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/slackrtm/server.py", line 127, in websocket_safe_read
2016-03-07T08:34:43.038250+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 378, in recv_data_frame
2016-03-07T08:34:43.038711+00:00 app[worker.1]:     return recv(self.sock, bufsize)
2016-03-07T08:34:43.038094+00:00 app[worker.1]:     data.append(self.websocket.recv())
2016-03-07T08:34:43.038096+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 348, in recv
2016-03-07T08:34:43.038230+00:00 app[worker.1]:     opcode, frame = self.recv_data_frame(control_frame)
2016-03-07T08:34:43.038338+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 410, in recv_frame
2016-03-07T08:34:43.038543+00:00 app[worker.1]:     header = self.recv_strict(2)
2016-03-07T08:34:43.038622+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 476, in _recv
2016-03-07T08:34:43.038759+00:00 app[worker.1]:     raise WebSocketConnectionClosedException("Connection is already closed.")
2016-03-07T08:34:43.038726+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_socket.py", line 89, in recv
2016-03-07T08:34:43.038788+00:00 app[worker.1]: websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
2016-03-07T08:34:43.038614+00:00 app[worker.1]:     bytes = self.recv(min(16384, shortage))
2016-03-07T08:34:43.785124+00:00 heroku[worker.1]: State changed from up to crashed
2016-03-07T08:34:43.775176+00:00 heroku[worker.1]: Process exited with status 1`

**Comment by jonathan-s** [comment]
Hi @hansott, 
Do you think you could set the following environment variable: `LIMBO_LOGLEVEL` to `DEBUG` and give me the traceback for that and I'll make sure to fix this as quick as possible.

**Comment by hansott** [comment]
```txt
Set LIMBO_LOGLEVEL config vars by hansott@hotmail.be
Release v6 created by hansott@hotmail.be
Restarting
State changed from up to starting
Stopping all processes with SIGTERM
Process exited with status 143
Starting process with command `python bin/limbo`
State changed from starting to up
2016-03-07 14:53:56,508:DEBUG:limbo.limbo:plugin: attaching message hook for alerts
2016-03-07 14:53:56,508:DEBUG:limbo.limbo:plugin: listing
2016-03-07 14:53:56,265:DEBUG:limbo.limbo:plugin: alerts
2016-03-07 14:53:56,264:DEBUG:limbo.limbo:config: {'token': '!HIDDEN!', 'loglevel': 'DEBUG'}
2016-03-07 14:53:56,510:DEBUG:limbo.limbo:plugin: devices
2016-03-07 14:53:56,512:DEBUG:limbo.limbo:plugin: attaching message hook for devices
2016-03-07 14:53:56,510:DEBUG:limbo.limbo:plugin: attaching message hook for listing
2016-03-07 14:53:56,265:DEBUG:limbo.limbo:plugindir: /app/limbo/plugins
2016-03-07 14:53:56,512:DEBUG:limbo.limbo:plugin: graph
2016-03-07 14:53:59,144:DEBUG:limbo.limbo:plugin: attaching message hook for graph
2016-03-07 14:53:59,145:DEBUG:limbo.limbo:plugin: attaching channel_joined hook for help
2016-03-07 14:53:59,145:DEBUG:limbo.limbo:plugin: attaching message hook for help
2016-03-07 14:53:59,144:DEBUG:limbo.limbo:plugin: help
2016-03-07 14:53:59,147:DEBUG:limbo.limbo:plugin: attaching message hook for services
2016-03-07 14:53:59,145:DEBUG:limbo.limbo:plugin: services
2016-03-07 14:54:01,498:DEBUG:limbo.limbo:got hello
2016-03-07 14:54:01,499:DEBUG:limbo.limbo:got reconnect_url
2016-03-07 14:54:01,499:DEBUG:limbo.limbo:got presence_change
2016-03-07 14:54:08,512:DEBUG:limbo.limbo:got pong
2016-03-07 14:54:15,526:DEBUG:limbo.limbo:got pong
2016-03-07 14:54:22,538:DEBUG:limbo.limbo:got pong
2016-03-07 14:54:29,563:DEBUG:limbo.limbo:got user_typing
2016-03-07 14:54:29,613:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.serverdensity.io
2016-03-07 14:54:29,563:DEBUG:limbo.limbo:got pong
2016-03-07 14:54:29,563:DEBUG:limbo.limbo:got message
2016-03-07 14:54:30,169:DEBUG:requests.packages.urllib3.connectionpool:"GET /inventory/devices?token=!HIDDEN! HTTP/1.1" 200 None
2016-03-07 14:54:30,449:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.serverdensity.io
2016-03-07 14:54:31,410:DEBUG:requests.packages.urllib3.connectionpool:"GET /metrics/definitions/5202d0501212ba673a0001ed?start=2016-03-07T12%3A54%3A30.447564&token=!HIDDEN!&end=2016-03-07T14%3A54%3A30.447564 HTTP/1.1" 200 None
2016-03-07 14:54:31,448:DEBUG:help:sdbot devices available server111
2016-03-07 14:54:31,486:DEBUG:limbo.limbo:got presence_change
Traceback (most recent call last):
  File "bin/limbo", line 17, in <module>
    main(args)
  File "/app/limbo/limbo.py", line 285, in main
  File "/app/limbo/limbo.py", line 181, in loop
    loop(server)
    events = server.slack.rtm_read()
  File "/app/.heroku/python/lib/python2.7/site-packages/slackrtm/client.py", line 23, in rtm_read
    data = [json.loads(d) for d in self.server.websocket_safe_read()]
  File "/app/.heroku/python/lib/python2.7/site-packages/slackrtm/server.py", line 127, in websocket_safe_read
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 348, in recv
    data.append(self.websocket.recv())
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 378, in recv_data_frame
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 410, in recv_frame
    frame = self.recv_frame()
    opcode, data = self.recv_data()
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
    return self.frame_buffer.recv_frame()
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_abnf.py", line 300, in recv_frame
    header = self.recv_strict(2)
    self.recv_header()
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_abnf.py", line 249, in recv_header
    bytes = self.recv(min(16384, shortage))
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_abnf.py", line 334, in recv_strict
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_core.py", line 476, in _recv
    return recv(self.sock, bufsize)
  File "/app/.heroku/python/lib/python2.7/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
Process exited with status 1
State changed from crashed to starting
State changed from up to crashed
```

I've replaced the access tokens with `!HIDDEN!`, if you need more information, shoot!

**Comment by jonathan-s** [comment]
My guess is that the output of available metrics is too big for slack to handle as a single text message. I'll investigate a bit further.

**Comment by hansott** [comment]
Thanks for the update!
